server:
  port: 8082
spring:
  application:
    name: leyou-upload-service
  servlet:
    multipart:
      max-file-size: 20MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
fdfs:
  connect-timeout: 601
  so-timeout: 1500
  thumb-image:
    height: 60
    width: 60
  tracker-list:
    - 192.168.187.10:22122