server:
  port: 8086
spring:
  application:
    name: leyou-msm-service
  rabbitmq:
    host: 192.168.187.10
    username: leyou
    password: 1234
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAItNxtDfk7MJMq # 你自己的accessKeyId
    accessKeySecret: HKUIDl21ZM7XoubErXjUFJq84dha8W # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_143714980 # 模板名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka